GET http://localhost:3000/users

###

GET http://localhost:3000/users/5ff50ea216a365e91a40437d

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "User",
    "quiz": {
        "name":"Test"
    },
    "attempted":[{
        "quizName": "Test",
        "completion": true,
        "score": 5
    }]
}

###
DELETE http://localhost:3000/users/5ff62dc706f16609dfd98f0d
###

PATCH http://localhost:3000/users/5ff61611d819db06ec023dd0
Content-Type: application/json

{
    "quiz": {
        "name":"empty"
    }
}